### ISSUE TITLE
Redirecting playback of 2.0 recordings to 2.3 breaks older audio-only sessions

### ISSUE THREAD

**Issue by steffen-moser** [bigbluebutton/bbb-playback#112]
**Describe the bug**
In PR bigbluebutton/bigbluebutton#11061, the new recording player 2.3 was configured as the default player for older recordings. This leads to a problem when older recordings have been done without video. 

**To Reproduce**
1. Install BBB 2.2.x 
2. Start a BBB meeting, do *not* use video
3. Record the meeting
4. Wait until the record is processed
5. Install BBB 2.3.x on a new server
6. Move the published recording from the BBB 2.2 to the BBB 2.3 server
7. Try to watch the recorded session on the new server

**Expected behavior**
The older recordings should still run in BBB 2.3.x even if there was no video stream.

**Actual behavior**
BBB playback 2.3 does not find a "video/webcams.webm" file in an audio-only session and shows a 404 to the user.

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Firefox, Chrome, Safari

**Additional context**
A quick fix for uns was un-doing bigbluebutton/bigbluebutton#11061. In this case, the old recordings still work, as version 2.0 of the player is used for them. But, of course, the newer player would be much better.  Renaming "audio/audio.webm" to "video/webcams.webm" would also work. I think the new player should be improved in a way that it also works with recordings which don't contain any webcam data.

**Comment by mudislandkid** [comment]
I am unfortunately having the same problem. I setup BBB 2.3 on a fresh ubuntu 18 server. I then transferred the recordings from my BBB 2.2 server. Any recordings creating since migration play fine. Any recordings from the previous server will load in the 2.3 player, it will show the slides and chat etc. But all have a BBB logo as the first slide and when I play I end up with a media error. I tried utilizing the workaround mentioned above by adding:

`location /playback/presentation/2.0/playback.html {
                return 301 /playback/presentation/2.0/playback.html?$query_string;
        }`

into /etc/bigbluebutton/nginx/presentation.nginx but that just ends up in a 404 error.

I've been trying to solve this for the last two days! Any help would be much appreciated!

Many Thanks
