### ISSUE TITLE
slide too small in landscape smartphone

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bbb-playback#32]
**Describe the bug**
The slide is almost invisible when place the Android smartphone in the landscape position.

**To Reproduce**
Start the 2.3 playback in Android smartphone, then rotate the phone 90 degree.

**Expected behavior**
The slide should be displayed much larger by default, although the user can expand the screen later by pinching in.

**Screenshots**
![Screenshot_20200620-102734のコピー](https://user-images.githubusercontent.com/45039819/85188584-d7237680-b2e2-11ea-81d8-09e8fa6ee861.jpg)

**Desktop (please complete the following information):**
Desktop is fine.

**Smartphone (please complete the following information):**
 - Device: Huawei P10lite
 - OS: Android
 - Browser Chrome, Firefox

**Additional context**
iPhone not tested.

**Comment by pedrobmarin** [comment]
That's because you are still getting the portrait view. Your mobile landscape width must be smaller than `600px` https://github.com/bigbluebutton/bbb-playback/blob/9fc4604661a607b4f52244716e5934bbf38bac47/src/styles/sizes.scss#L2
For such small device I recommend using the portrait mode or hiding the side panel (top left **-** button) and swapping the content the select video or presentation.
If that's not enough, feel free to try lower width thresholds for the style media queries

**Comment by hiroshisuga** [comment]
Thanks for the solution. It worked!

I would still like it to be more intuitive. When students turn the mobile into landscape mode, they usually expect a larger slide appearing immediately. The playback 2.0 behaves like that anyhow. 

An alternative is to implement the full-screen mode, which I am sure you already have in your mind.

**Comment by pedrobmarin** [comment]
I guess we can lower down the media query limit to `480px`. `600px` seemed enough on my tests but I believe I just missed the smaller ones.

**Comment by pedrobmarin** [comment]
Modified at https://github.com/bigbluebutton/bbb-playback/commit/982985ea90a87d9776d944a8d79c7c177c726ee3.

**Comment by hiroshisuga** [comment]
Yes, this has fixed the problem. Thanks! 
It's weird that my Huawei P10lite' screen (5.2 inches 1920 x 1080 pixels) is not that small. On the other hand, my old ZTE BladeV6 has a way smaller screen (5 inches 1280×720 pixels), but no problem with 600px.
